name: 'Scripted kubernetes deployment'
description: 'Scripted kubernetes deployment with GitHub Actions'
author: 'slaskinc'
inputs:
  k8sConfig:
    description: 'Kubernetes config'
    required: true
  scriptPath:
    description: "Path to the deployment to apply"
    default: '../operations/deploy.js'
runs:
  using: node16
  main: lib/slask.js
