name: 'Scripted kubernetes deployment'
description: 'Scripted kubernetes deployment with GitHub Actions'
author: 'slaskinc'
inputs:
  k8sConfig:
    description: 'Kubernetes config'
    required: true
  scriptPath:
    description: "Path to the deployment to apply"
    default: './operations/deploy.config.js'
runs:
  using: node16
  main: lib/slask.js
  # using: 'composite'
  # steps:
  #   - shell: bash
  #     env:
  #       K8SCONFIG: ${{ inputs.k8sConfig}}
  #     working-directory: ${{ inputs.scriptPath}}
  #     run: npm i && npm run deploy
  #   - uses: 'node16'
      