name: "slaska"
on: [push, pull_request]

jobs:
  slask:
    runs-on: self-hosted
    env:
      NAMESPACE: slaskar
    steps:
    - uses: actions/checkout@v3
    - name: Deploy scripted application
      uses: ./
      with:
        k8sConfig: ${{ secrets.K8S_CONFIG }}

        