name: "slaska"
on: [push, pull_request]

jobs:
  slask:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "npm ci"
      run: npm ci
    - name: slaskit
      uses: ./
      with:
        k8sConfig: ${{ secrets.K8S_CONFIG }}
        